name: flutter_app_preferences
description: "A simple package to manage app preferences and get notifications when something changes."
version: 0.3.3
homepage: https://nikodembernat.com
repository: https://github.com/n-bernat/flutter_app_preferences
issue_tracker: https://github.com/n-bernat/flutter_app_preferences/issues
topics:
  - persistence
  - shared-preferences
  - storage

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0

dev_dependencies:
  leancode_lint: ^14.1.0
