name: flutter_app_preferences
description: "A simple package to manage app preferences and get notifications when something changes."
version: 0.1.0
homepage: https://nikodembernat.com

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  leancode_lint: ^13.0.0
